trigger:
  branches:
    include:
      - main  # Trigger the pipeline when code is pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based virtual machine for the build agent

stages:

  # Stage 1: Checkout the code from GitHub
  - stage: CheckoutCode
    displayName: 'Checkout Code'
    jobs:
      - job: Checkout
        displayName: 'Checkout Code Job'
        steps:
          - checkout: self  # Checkout the code from the repository
            displayName: 'Checkout Code'
