trigger:
  branches:
    include:
      - main  # or the branch where the code is pushed

pool:
  vmImage: 'ubuntu-latest'  # We will use an Ubuntu agent for the build

stages:
  # Stage 1: Checkout the code
  - stage: CheckoutCode
    jobs:
      - job: Checkout
        steps:
          - task: Checkout@1  # Checkout the code from GitHub
            displayName: 'Checkout Code'

