trigger:
  branches:
    include:
      - main  # Trigger the pipeline when code is pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based virtual machine for the build agent

stages:
  # Stage 1: Checkout the code
  - stage: CheckoutCode
    jobs:
      - job: Checkout
        steps:
          - task: Checkout@2  # Use the latest version for checking out the code
            displayName: 'Checkout Code'
